"""initial

Revision ID: 273d776fb757
Revises:
Create Date: 2025-11-10 13:50:47.450656

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '273d776fb757'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('first_name', sa.String(length=255), nullable=False),
        sa.Column('last_name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=True),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('telegram_id', sa.String(length=64), nullable=True),
        sa.Column(
            'preferred_channels',
            sa.ARRAY(sa.Enum('EMAIL', 'SMS', 'TELEGRAM', name='notification_channel')),
            nullable=False,
        ),
        sa.Column('uid', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('uid', name=op.f('pk_users')),
        sa.UniqueConstraint('email', name=op.f('uq_users_email')),
        sa.UniqueConstraint('phone', name=op.f('uq_users_phone')),
        sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id')),
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)

    op.create_table(
        'notifications',
        sa.Column('user_uid', sa.UUID(), nullable=False),
        sa.Column('message', sa.String(length=1024), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status'), nullable=False),
        sa.Column('sent_channel', sa.Enum('EMAIL', 'SMS', 'TELEGRAM', name='notification_channel'), nullable=True),
        sa.Column('uid', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], name=op.f('fk_notifications_user_uid_users')),
        sa.PrimaryKeyConstraint('uid', name=op.f('pk_notifications')),
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_uid'), ['user_uid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_uid'))

    op.drop_table('notifications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))

    op.drop_table('users')
    # ### end Alembic commands ###
